services:
  colocations-app:
    build: .
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - DB_HOST=colocations-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres123
      - DB_NAME=colocations_db
      - JWT_SECRET=change_me_in_production
      - JWT_EXPIRES_IN=24h
      - CLIENT_ORIGIN=http://localhost:3004
      - PUBLIC_BASE_URL=http://localhost:3002
    depends_on:
      - colocations-db
    networks:
      backend-network:
        aliases:
          - colocations-app
    volumes:
      - ./uploads:/app/uploads

  colocations-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: colocations_db
    volumes:
      - colocations-db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend-network

networks:
  backend-network:
    external: true
    name: backend-network

volumes:
  colocations-db-data:

