-- Colocations Service schema
-- UUIDs are generated by the application (no DB extension required).

BEGIN;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 1) LOCALISATIONS
CREATE TABLE locations (
  id          UUID PRIMARY KEY,
  city        TEXT NOT NULL,
  postal_code TEXT NOT NULL,
  address     TEXT NULL,
  lat         DOUBLE PRECISION NULL,
  lng         DOUBLE PRECISION NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_locations_city_postal_code ON locations(city, postal_code);
CREATE INDEX idx_locations_postal_code ON locations(postal_code);

-- 2) ANNONCES
CREATE TABLE listings (
  id               UUID PRIMARY KEY,

  owner_user_id    UUID NOT NULL, -- external ref to users-service (no FK)
  location_id      UUID NOT NULL REFERENCES locations(id) ON DELETE RESTRICT,

  title            TEXT NOT NULL,
  description      TEXT NOT NULL,

  rent_amount      INTEGER NOT NULL CHECK (rent_amount >= 0),
  charges_included BOOLEAN NOT NULL DEFAULT FALSE,
  surface_m2       INTEGER NULL CHECK (surface_m2 IS NULL OR surface_m2 > 0),

  housing_type     TEXT NOT NULL CHECK (housing_type IN ('ROOM','STUDIO','FLAT','HOUSE','OTHER')),

  available_from   DATE NOT NULL,
  available_to     DATE NULL,
  min_duration_months INTEGER NULL CHECK (min_duration_months IS NULL OR min_duration_months >= 0),

  status           TEXT NOT NULL DEFAULT 'DRAFT'
                   CHECK (status IN ('DRAFT','PUBLISHED','PAUSED','CLOSED')),

  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),

  CHECK (available_to IS NULL OR available_to >= available_from)
);

CREATE INDEX idx_listings_status ON listings(status);
CREATE INDEX idx_listings_location_status ON listings(location_id, status);
CREATE INDEX idx_listings_rent_status ON listings(rent_amount, status);
CREATE INDEX idx_listings_available_from_status ON listings(available_from, status);
CREATE INDEX idx_listings_owner_status ON listings(owner_user_id, status);
CREATE INDEX idx_listings_search ON listings(location_id, rent_amount, status);

DROP TRIGGER IF EXISTS trg_listings_updated_at ON listings;
CREATE TRIGGER trg_listings_updated_at
BEFORE UPDATE ON listings
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE listing_ambience_rules (
  listing_id UUID PRIMARY KEY REFERENCES listings(id) ON DELETE CASCADE,
  ambience   TEXT NULL,
  rules      TEXT NULL
);

CREATE TABLE listing_photos (
  id         UUID PRIMARY KEY,
  listing_id UUID NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
  url        TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_listing_photos_listing_id ON listing_photos(listing_id);
CREATE INDEX idx_listing_photos_listing_sort ON listing_photos(listing_id, sort_order);

-- 3) EQUIPEMENTS
CREATE TABLE listing_equipments (
  id    UUID PRIMARY KEY,
  code  TEXT NOT NULL UNIQUE,
  label TEXT NOT NULL
);

CREATE TABLE listing_equipment_map (
  listing_id   UUID NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
  equipment_id UUID NOT NULL REFERENCES listing_equipments(id) ON DELETE RESTRICT,
  PRIMARY KEY (listing_id, equipment_id)
);

CREATE INDEX idx_listing_equipment_map_equipment_id ON listing_equipment_map(equipment_id);

-- 4) PREFS SOUHAITEES POUR FUTURS COLOCATAIRES (cote annonce)
CREATE TABLE listing_candidate_requirements (
  listing_id        UUID PRIMARY KEY REFERENCES listings(id) ON DELETE CASCADE,
  preferred_age_min INTEGER NULL CHECK (preferred_age_min IS NULL OR preferred_age_min >= 0),
  preferred_age_max INTEGER NULL CHECK (preferred_age_max IS NULL OR preferred_age_max >= 0),
  preferred_gender  TEXT NULL CHECK (preferred_gender IN ('F','M','NON_BINARY','OTHER','ANY')),
  preferred_status  TEXT NULL CHECK (preferred_status IN ('STUDENT','PRO','OTHER','ANY')),
  notes             TEXT NULL,
  CHECK (preferred_age_min IS NULL OR preferred_age_max IS NULL OR preferred_age_max >= preferred_age_min)
);

CREATE INDEX idx_lcr_preferred_gender ON listing_candidate_requirements(preferred_gender);
CREATE INDEX idx_lcr_preferred_status ON listing_candidate_requirements(preferred_status);

CREATE TABLE listing_lifestyle_requirements (
  listing_id UUID NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
  key        TEXT NOT NULL,
  value      TEXT NOT NULL,
  PRIMARY KEY (listing_id, key)
);

CREATE INDEX idx_llr_key ON listing_lifestyle_requirements(key);
CREATE INDEX idx_llr_key_value ON listing_lifestyle_requirements(key, value);

-- 5) FAVORIS
CREATE TABLE favorites (
  user_id    UUID NOT NULL, -- external ref to users-service (no FK)
  listing_id UUID NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, listing_id)
);

CREATE INDEX idx_favorites_listing_id ON favorites(listing_id);
CREATE INDEX idx_favorites_user_created_at ON favorites(user_id, created_at);

-- 6) CANDIDATURES
CREATE TABLE applications (
  id                UUID PRIMARY KEY,
  listing_id        UUID NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
  applicant_user_id UUID NOT NULL, -- external ref to users-service (no FK)
  message           TEXT NULL,
  status            TEXT NOT NULL DEFAULT 'SENT'
                    CHECK (status IN ('SENT','ACCEPTED','REJECTED','WITHDRAWN')),
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX ux_applications_listing_applicant ON applications(listing_id, applicant_user_id);
CREATE INDEX idx_applications_listing_status ON applications(listing_id, status);
CREATE INDEX idx_applications_applicant_status ON applications(applicant_user_id, status);
CREATE INDEX idx_applications_created_at ON applications(created_at);

DROP TRIGGER IF EXISTS trg_applications_updated_at ON applications;
CREATE TRIGGER trg_applications_updated_at
BEFORE UPDATE ON applications
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 7) MATCHES / SUGGESTIONS (optionnel MVP)
CREATE TABLE matches (
  id         UUID PRIMARY KEY,
  listing_id UUID NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
  user_id    UUID NOT NULL, -- external ref to users-service (no FK)
  score      INTEGER NULL CHECK (score IS NULL OR score >= 0),
  status     TEXT NOT NULL DEFAULT 'SUGGESTED'
             CHECK (status IN ('SUGGESTED','LIKED','DISLIKED','MUTUAL')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX ux_matches_listing_user ON matches(listing_id, user_id);
CREATE INDEX idx_matches_user_status ON matches(user_id, status);
CREATE INDEX idx_matches_listing_status ON matches(listing_id, status);
CREATE INDEX idx_matches_user_score ON matches(user_id, score);

COMMIT;

