-- Users Service schema
-- UUIDs are generated by the application (no DB extension required).

BEGIN;

-- Keep updated_at consistent without relying on the app everywhere.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 1) USERS / AUTH
CREATE TABLE users (
  id            UUID PRIMARY KEY,
  username      TEXT NOT NULL UNIQUE,
  email         TEXT NOT NULL UNIQUE CHECK (email = lower(email)),
  password_hash TEXT NOT NULL,
  status        TEXT NOT NULL DEFAULT 'ACTIVE'
               CHECK (status IN ('ACTIVE','SUSPENDED','DELETED')),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_users_created_at ON users(created_at);

DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Optional: sessions / refresh tokens
CREATE TABLE user_sessions (
  id                 UUID PRIMARY KEY,
  user_id            UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  refresh_token_hash TEXT NOT NULL,
  expires_at         TIMESTAMPTZ NOT NULL,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  revoked_at         TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX ux_user_sessions_refresh_token_hash ON user_sessions(refresh_token_hash);
CREATE INDEX idx_user_sessions_user_id ON user_sessions(user_id);
CREATE INDEX idx_user_sessions_expires_at ON user_sessions(expires_at);

-- 2) PROFILES
CREATE TABLE profiles (
  user_id           UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  birth_date        DATE NULL,
  gender            TEXT NULL CHECK (gender IN ('F','M','NON_BINARY','OTHER')),
  occupation_status TEXT NULL CHECK (occupation_status IN ('STUDENT','PRO','OTHER')),
  role              TEXT NULL CHECK (role IN ('OWNER','SEEKER')),
  bio               TEXT NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_profiles_occupation_status ON profiles(occupation_status);

DROP TRIGGER IF EXISTS trg_profiles_updated_at ON profiles;
CREATE TRIGGER trg_profiles_updated_at
BEFORE UPDATE ON profiles
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 3) PREFERENCES (MVP)
CREATE TABLE profile_preferences (
  user_id         UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  budget_min      INTEGER NULL CHECK (budget_min IS NULL OR budget_min >= 0),
  budget_max      INTEGER NULL CHECK (budget_max IS NULL OR budget_max >= 0),
  location        TEXT NULL,
  smoking         TEXT NULL CHECK (smoking IN ('NO','YES','OUTSIDE_ONLY')),
  pets            TEXT NULL CHECK (pets IN ('NO','YES','OK_WITH_PETS')),
  noise_level     TEXT NULL CHECK (noise_level IN ('CALM','NORMAL','FESTIVE')),
  guests_policy   TEXT NULL CHECK (guests_policy IN ('NO','OCCASIONAL','OK')),
  lifestyle_notes TEXT NULL,
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (budget_min IS NULL OR budget_max IS NULL OR budget_max >= budget_min)
);

DROP TRIGGER IF EXISTS trg_profile_preferences_updated_at ON profile_preferences;
CREATE TRIGGER trg_profile_preferences_updated_at
BEFORE UPDATE ON profile_preferences
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMIT;
