-- Messages Service schema
-- UUIDs are generated by the application (no DB extension required).

BEGIN;

CREATE TABLE conversations (
  id         UUID PRIMARY KEY,
  listing_id UUID NULL, -- external ref to colocations-service (no FK)
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_conversations_created_at ON conversations(created_at);
CREATE INDEX idx_conversations_listing_id ON conversations(listing_id);

CREATE TABLE conversation_participants (
  conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  user_id         UUID NOT NULL, -- external ref to users-service (no FK)
  PRIMARY KEY (conversation_id, user_id)
);

CREATE INDEX idx_conversation_participants_user_id ON conversation_participants(user_id);

CREATE TABLE messages (
  id              UUID PRIMARY KEY,
  conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  sender_user_id  UUID NOT NULL, -- external ref to users-service (no FK)
  body            TEXT NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  read_at         TIMESTAMPTZ NULL
);

CREATE INDEX idx_messages_conversation_created_at ON messages(conversation_id, created_at);
CREATE INDEX idx_messages_sender_created_at ON messages(sender_user_id, created_at);

COMMIT;

